name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Show files
        run: |
          Get-ChildItem .
          Get-ChildItem plugins
          Get-ChildItem plugins\tray_manager
          Get-ChildItem plugins\tray_manager\packages
          Get-ChildItem plugins\tray_manager\packages\tray_manager

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Check tray_manager path
        run: |
          if (Test-Path "plugins\tray_manager\packages\tray_manager") {
            Write-Output "FOUND tray_manager"
          } else {
            Write-Output "tray_manager NOT FOUND"
            exit 1
          }

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release
